# Generated by Django 5.2.17 on 2026-09-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The blog's display title.", max_length=120)),
                ('slug', models.SlugField(help_text='Becomes the subdomain: <slug>.postly.com', max_length=63, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Generated from the title on first save, then left alone so published URLs stay stable.', max_length=255)),
                ('content', models.TextField(blank=True, help_text='HTML produced by the editor.')),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.site')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['site', 'status'], name='blog_post_site_id_42804c_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'slug'), name='unique_post_slug_per_site')],
            },
        ),
    ]
