# Generated by Django 5.2.17 on 2026-09-16 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='accent_hue',
            field=models.PositiveSmallIntegerField(blank=True, help_text="An OKLCH hue, 0-360, for links and accents. Null keeps the theme's own accent. Only the hue is the writer's to choose — lightness and chroma come from the theme, which is what keeps contrast legible at every setting.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AddField(
            model_name='site',
            name='appearance',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'Follow the reader')], default='light', help_text="Light, dark, or whichever the reader's system asks for.", max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='font_pairing',
            field=models.CharField(choices=[('editorial', 'Editorial — serif headings, serif body'), ('clean', 'Clean — serif headings, sans body'), ('plain', 'Plain — sans headings, sans body')], default='editorial', help_text='Which of the loaded font families the blog sets type in.', max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='theme',
            field=models.CharField(choices=[('paper', 'Paper'), ('slate', 'Slate'), ('sepia', 'Sepia'), ('mono', 'Mono')], default='paper', help_text='Which named palette the published blog is rendered in.', max_length=16),
        ),
    ]
