# Generated by Django 5.2.17 on 2026-09-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_site_accent_hue_site_appearance_site_font_pairing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='tagline',
            field=models.CharField(blank=True, help_text="One line under the blog's name in the masthead. A subtitle, not a description — the long version is `description`.", max_length=160),
        ),
    ]
