# Generated by Django 5.2.17 on 2026-09-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_site_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='subscriptions_enabled',
            field=models.BooleanField(default=False, help_text='Whether readers are offered an email subscription.'),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], default='pending', max_length=16)),
                ('unsubscribe_token', models.CharField(editable=False, help_text='Unguessable, permanent, and enough on its own to unsubscribe — an unsubscribe link cannot ask a reader to log in.', max_length=64, unique=True)),
                ('source', models.CharField(choices=[('index', 'Blog index'), ('post', 'End of a post'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(help_text='Deleting the blog deletes its list.', on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='blog.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'status'], name='blog_subscr_site_id_078ef8_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'email'), name='unique_subscriber_per_site')],
            },
        ),
    ]
