# Generated by Django 5.2.17 on 2026-09-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_site_subscriptions_enabled_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
