# Generated by Django 5.2.17 on 2026-09-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_subscriber_confirmation_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting to send'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('scheduled_for', models.DateTimeField(help_text='Not before this. The gap between publishing and sending is the window in which a writer can unpublish a typo and have nothing go out.')),
                ('last_subscriber_id', models.PositiveBigIntegerField(default=0, help_text='Highest subscriber id already mailed. A resumed run starts after this rather than at the beginning.')),
                ('recipient_count', models.PositiveIntegerField(default=0, help_text='Confirmed subscribers when the run started.')),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.OneToOneField(help_text='One notification per post, forever. This is what makes republishing unable to mail anybody twice.', on_delete=django.db.models.deletion.CASCADE, related_name='email', to='blog.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='blog_postem_status_81058c_idx')],
            },
        ),
    ]
