# Generated by Django 5.2.17 on 2026-09-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_subscriber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(help_text="The blog's address: a path on the app today, a subdomain once BLOG_DOMAIN is set. See blog/addresses.py.", max_length=63, unique=True),
        ),
    ]
