# Generated by Django 5.2.17 on 2026-09-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Optional. The blog falls back to an initials circle in the theme's accent when this is empty.", null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="A short 'About' note, shown beside the posts on the public blog. Around 300 characters — it is a paragraph, not a page.", max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email_publicly',
            field=models.BooleanField(default=False, help_text='Whether the public blog shows this address. Off by default: publishing an address is a decision, not a side effect of having one.'),
        ),
    ]
