# Generated by Django 5.2.17 on 2026-09-17 04:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Shown next to the byline on the writer's public blog.", null=True, upload_to=accounts.models.avatar_path),
        ),
    ]
