# Generated by Django 5.2.17 on 2026-09-17 10:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_bio_user_show_email_publicly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Optional. The blog falls back to an initials circle in the theme's accent when this is empty.", null=True, upload_to=accounts.models.avatar_path),
        ),
    ]
